### ISSUE TITLE
Common Library v1.0.0-alpha.2

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#229]
- [x] Update wasmtime to (almost) lastest master (#6662)
- [x] Remove the service builder (#6557)
- [x] Better handling of stable-only build (#6569)
- [x] Remove clear_on_drop from browser util crate (#6710)
- [x] Add 4 as address type of ss58 for Katal Chain (#6713)
- [x] \[CI\]Chaostest suite initiation (#5793)
- [x] Support using system storage directly for EVM balance and nonce (#6659)
- [x] Augmented node template docs (#6721)
- [x] Switching from git back to released versions for wasmtime, fix cargo-unleash (#6722)
- [x] adding changelog (#6728)
- [x] fixing CI
- [x] remove breaking excepts
- [x] grandpa: allow noting that the set has stalled (#6725)
- [x] Name all the tasks! (#6726)
- [x] Add the Substrate Service Tasks dashboard (#6665)
- [x] seal: Fail instantiate if new contract is below subsistence threshold (#6719)
- [x] Remove Unpin requirement for Slots (#6711)
- [x] pallet-evm: add support for tuple-based precompile declarations (#6681)
- [x] prometheus: don't use protobuf feature (#6744)
- [x] Use node_template_runtime::opaque::Block instead of node_template_runtime::Block (#6737)
- [x] Various small improvements to service construction. (#6738)
- [x] Remove unused node template deps (#6748)
- [x] Replace Process.toml with json (#6740)
- [x] Update parity-scale-codec to prepare for breaking rustc release (#6746)
- [x] seal: Add benchmarks for dispatchables (#6715)
- [x] client/network: Adjust wording (#6755)
- [x] Add a back-pressure-friendly alternative to NetworkService::write_notifications 🎉 (#6692)
- [x] Cleanup our sort usage (#6754)
- [x] Allow \`PostDispatchInfo\` to disable fees (#6749)
- [x] benchmarks! macro: factorize instance usage. (#6750)
- [x] client/network: Add peers to DHT only if protocols match (#6549)
- [x] Add \`memory-tracker\` feature to \`sp-trie\` to fix wasm panic (#6745)
- [x] support custom ss58addressformat in from_ss58check_with_version (#5526)
- [x] Add a \`DefaultQueue\` type alias to remove the need to use \`sp_api::TransactionFor\` (#6761)
- [x] Ignore flaky test (#6767)
- [x] Add "✅ Successfully mined block" log message (#6764)
- [x] pallet-evm: add builtin support for the four basic Ethereum precompiles (#6743)
- [x] Rename task name to stick to the default naming scheme (#6768)
- [x] BABE slot and epoch event notifications (#6563)
- [x] Update Balances Pallet to use \`WeightInfo\` (#6610)
- [x] Fix graceful shutdown skipped if future ends with error (#6769)
- [x] Fix link (#6775)
- [x] Allow blacklisting blocks from being finalized again after block revert (#6301)
- [x] Order delta before calculating the storage root (#6780)
- [x] Don't close inbound notifications substreams immediately (#6781)
- [x] client/network: Expose DHT query duration to Prometheus (#6784)
- [x] Fix transaction payment runtime api (#6792)
- [x] Bump elliptic from 6.5.2 to 6.5.3 in /.maintain/chaostest (#6791)
- [x] client/network: Fix wrong metric help text (#6794)
- [x] seal: Fix and improve error reporting (#6773)
- [x] Improve Benchmark Writer: Remove Unused Components, Remove Multiply by Zero, Files Split by Pallet (#6785)
- [x] Add integrity test for slash defer duration (#6782)
- [x] Convert spaces to tabs (#6799)
- [x] Add details to legacy requests (#6747)
- [x] Add ss58 address for Subsocial (#6800)
- [x] Add mutate_exists to StorageDoubleMap. (#6704)
- [x] pallet-democracy use of weightinfo (#6783)
- [x] Use DNS hostnames for flaming fir bootnodes (#6807)
- [x] Fix warning being printed by authority-discovery (#6820)
- [x] Better default balances weights (#6813)
- [x] Remove generation of instance trait by decl_storage. (#6812)
- [x] Successful \`note_imminent_preimage\` is free (#6793)
- [x] service: remove collection of system/process metrics (#6822)
- [x] Fix legacy substream fallback not working (#6826)
- [x] grandpa: never overwrite current rounds voter state (#6823)
- [x] Add RPC Builder to Substrate Node Template (#6808)
- [x] Delay network startup to after complete initialization (#6833)
