### ISSUE TITLE
Darwinia RC6

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#244]
Fast Forward to https://github.com/paritytech/substrate/tree/ed4f7a113073c08cba9020c3f0dd6c8f0441f857, to support evm and frontier.

**Comment by AurevoirXavier** [comment]
- [x] De-alias frame_system in node template runtime (#6829)
- [x] Allow task manager to have children (#6771)
- [x] De-alias pallets in node template runtime (#6836)
- [x] grandpa: fix enacting forced changes with no delay (#6828)
- [x] Renamed add_children to add_child since it adds only one child (#6838)
- [x] Revalidate transactions only on latest best block (#6824)
- [x] Fix \`wait_for_blocks\` counting blocks that didn't go through consensus (#6850)
- [x] pallet-evm: move gas price check to execute_evm (#6837)
- [ ] Update pinned wasm-bindgen dependency (#6861)
- [ ] Add Subscription RPC for Grandpa Finality (#5732)
- [ ] Remove minimum_validator_count stale const (#6864)
- [x] seal: Change prefix and module name from "ext_" to "seal_" for contract callable functions (#6798)
- [x] grandpa: log errors and grandpa unexpected conclusion (#6867)
- [ ] Custom Codec Implenetation for NPoS Election (#6720)
- [x] state_getSize RPC for storage maps (#6847)
- [x] Block packet size limit (#6398)
- [x] Move to upstream wasmtime, refactor globals snapshot  (#6759)
- [x] grandpa: change some logging from trace to debug (#6872)
- [ ] Fix wrong staking doc about transaction payment. (#6873)
- [x] docs: convert code of conduct to markdown (#6878)
- [x] Add Phala Network SS58 address type (#6758)
- [x] docs: fix references to code of conduct document (#6879)
- [x] Fuse the import queue receiver (#6876)
- [x] Implement 'transactional' annotation for runtime functions. (#6763)
- [x] Add a warning if users pass --sentry or --sentry-nodes (#6779)
- [x] pallet-evm: fix wrong logic in mutate_account_basic (#6786)
- [ ] Implement tracing::Event handling & parent_id for spans and events (#6672)
- [x] Add async test helper to timeout and provide a task_executor automatically (#6651)
- [ ] client/authority-discovery: Introduce AuthorityDiscoveryService (#6760)
- [x] Make \`HexDisplay\` useable in \`no_std\` (#6883)
