### ISSUE TITLE
Migrate All Pallets to Attribute Macro

### ISSUE THREAD

**Issue by songtianyi** [darwinia-network/darwinia-common#561]
Here is the list of pallet and their status, if you want to migrate one you can put your name after it to avoid duplicated work.
some helpful guidelines to do the migration: https://crates.parity.io/frame_support/attr.pallet.html#upgrade-guidelines
some helpful guidelines to review a migration: https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines

- [x] darwinia-crab-backing @songtianyi #560 
- [x] darwinia-crab-issuing @songtianyi #568 
- [x] darwinia-balances @AurevoirXavier #593 
- [x] darwinia-tron-backing @AurevoirXavier #610
- [x] darwinia-vesting @AurevoirXavier #586
- [x] darwinia-ethereum-backing @AurevoirXavier #611
- [ ] darwinia-ethereum-issuing @AurevoirXavier 
- [ ] darwinia-relayer-game
- [ ] darwinia-relay-authorities
- [x] darwinia-staking @AurevoirXavier #924
- [x] darwinia-header-mmr @AurevoirXavier #613
- [x] darwinia-evm @AsceticBear  #648 
- [x] dvm-dynamic-fee @AurevoirXavier @AsceticBear #644
- [x] dvm-ethereum @AsceticBear #649

**Comment by AurevoirXavier** [comment]
And I propose this style:

```rust
// LICENSE

//! # Module Introduction

//(ignore this in real code) pub import don't need comment
pub use pallet::*;
pub use weights::WeightInfo;

//(ignore this in real code) test module above others
#[cfg(test)]
mod mock;
#[cfg(test)]
mod tests;

#[frame_support::pallet]
pub mod pallet {
	//(ignore this in real code) pub mod types go first
	pub mod types {
		//(ignore this in real code) all import need a comment, easy for code review
		// --- darwinia ---
		use super::*;

		// Generic type
		pub type AccountId<T> = <T as frame_system::Config>::AccountId;
		// Simple type
		pub type SimpleNum = u128;
	}
	pub use types::*;

	//(ignore this in real code) imports go second
	//(ignore this in real code) all import need a comment, easy for code review
	// --- substrate ---
	use frame_support::pallet_prelude::*;
	use frame_system::pallet_prelude::*;
	//(ignore this in real code) all import need a comment, easy for code review
	// --- darwinia ---
	use crate::weights::WeightInfo;

	//(ignore this in real code) trait goes third
	#[pallet::config]
	pub trait Config: frame_system::Config {
		//(ignore this in real code) substrate framework types here
		// --- substrate ---
		type Event: From<Event<Self>> + IsType<<Self as frame_system::Config>::Event>;
		type WeightInfo: WeightInfo;
		//(ignore this in real code) custom types here
		// --- darwinia ---
		#[pallet::constant]
		type ModuleId: Get<ModuleId>;
	}

	//(ignore this in real code) event goes forth
	#[pallet::event]
	pub enum Event<T: Config> {
		//(ignore this in real code) need to place a `\` before the  bracket, cause these comment will generate the docs
		/// Dummy Event. \[who\]
		DummyEvent(AccountId<T>),
	}

	//(ignore this in real code) error goes fifth
	pub enum Error<T> {}

	//(ignore this in real code) storages go sixth
	//(ignore this in real code) keep visibility simple as `pub` or empty, if necessary then `pub (sup)` or `pub (crate)`
	#[pallet::storage]
	#[pallet::getter(fn total_mapped_ring)]
	pub type TotalMappedRing<T: Config> = StorageValue<_, MappedRing>;

	//(ignore this in real code) genesis config goes seventh, if this is a complex struct `impl Default` manually
	#[cfg_attr(feature = "std", derive(Default))]
	#[pallet::genesis_config]
	pub struct GenesisConfig {
		pub total_mapped_ring: MappedRing,
	}
	//(ignore this in real code) and I recommend not leave a empty line between struct and its own impl
	#[pallet::genesis_build]
	impl<T: Config> GenesisBuild<T> for GenesisConfig {
		fn build(&self) {
			let _ = T::RingCurrency::make_free_balance_be(
				&T::ModuleId::get().into_account(),
				T::RingCurrency::minimum_balance(),
			);

			<TotalMappedRing<T>>::put(self.total_mapped_ring);
		}
	}

	//(ignore this in real code) dispatch calls go last
	#[pallet::pallet]
	pub struct Pallet<T>(_);
	//(ignore this in real code) and I recommend not leave a empty line between struct and its own impl
	#[pallet::hooks]
	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {}
	//(ignore this in real code) and I recommend not leave a empty line between struct and its own impl
	#[pallet::call]
	impl<T: Config> Pallet<T> {}
}
```

**Comment by HackFisher** [comment]
Closing and move to wiki: https://github.com/darwinia-network/darwinia/wiki#how-to-migrate-pallet-to-attribute-macro-style

**Comment by AurevoirXavier** [comment]
Some pallets will be removed later.
