### ISSUE TITLE
Bench All Pallets

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#845]
Generating the new weight for each pallet.

`darwinia-staking` can be ignored which is quite hard to mock.

## TODO
- [ ] balances @AurevoirXavier https://github.com/paritytech/substrate/blob/master/frame/balances/src/benchmarking.rs
- [x] bridge/bsc
- [ ] bridge/ethereum
- [ ] bridge/relay-authorities
- [ ] bridge/relayer-game
- [ ] claims @AsceticBear 
- [ ] democracy @AsceticBear https://github.com/paritytech/substrate/blob/master/frame/democracy/src/benchmarking.rs
- [ ] dvm @AsceticBear 
- [ ] dvm-dynamic-fee @AsceticBear 
- [ ] elections-phragmen @AsceticBear https://github.com/paritytech/substrate/blob/master/frame/elections-phragmen/src/benchmarking.rs
- [x] evm
- [x] fee-market
- [ ] header-mmr
- [ ] vesting @AsceticBear https://github.com/paritytech/substrate/blob/master/frame/vesting/src/benchmarking.rs
- [ ] whomhole/backing/ethereum
- [x] whomhole/backing/s2s
- [x] whomhole/issuing/ethereum
- [x] whomhole/issuing/s2s

**Comment by AurevoirXavier** [comment]
@AsceticBear Could you pick this?

**Comment by AsceticBear** [comment]
Yep, I can. Can you add more descriptions?

**Comment by AurevoirXavier** [comment]
> Yep, I can. Can you add more descriptions?

Updated.
